name: Crystal CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: [latest, nightly]
    runs-on: ${{ matrix.os  }}
    steps:
      - name: Install duckdb
        run: brew install duckdb
      - name: Set Linux shared library path
        if: ${{ runner.os == 'Linux' }}
        run: echo LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib/
      - name: Set MacOS shared library path
        if: ${{ runner.os == 'MacOS' }}
        run: echo DYLD_LIBRARY_PATH=/usr/local/lib/
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec