name: Crystal CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    env:
      DYLD_LIBRARY_PATH: /usr/local/lib/
      CRYSTAL_LIBRARY_PATH: /usr/local/lib/
    steps:
      - name: Install duckdb and crystal
        run: |
          brew update
          brew install duckdb
          brew install crystal
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec